/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meylism_sparser_Sparser */

#ifndef _Included_com_meylism_sparser_Sparser
#define _Included_com_meylism_sparser_Sparser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_meylism_sparser_Sparser
 * Method:    filter
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_meylism_sparser_Sparser_filter
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_meylism_sparser_Sparser
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_meylism_sparser_Sparser_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
